### ISSUE TITLE
Complete: TODOs

### ISSUE THREAD

**Issue by percymamedy** [findbrok/laravel-watson-translate#5]
Complete these TODOs.

- [x] Create Translation Model
- [x] Delete Translation Model

**Comment by namelivia** [comment]
I could take this one

**Comment by percymamedy** [comment]
Most welcome

**Comment by namelivia** [comment]
Implementing the create method would require making changes on the Bridge, it seems that it has json Accept header by default. But the create method requires a different header [as seen in the documentation](https://www.ibm.com/watson/developercloud/language-translator/api/v2/#create-model).

As this is on a different repo. Should I create a new issue there? Can it have the hacktoberfest tag aswell?

**Comment by percymamedy** [comment]
Thanks a lot !!
